# Generated by Django 5.1.4 on 2024-12-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('flightnumber', models.CharField(max_length=10)),
                ('class_flight', models.CharField(choices=[('economy', 'Economy Class'), ('premium_economy', 'Premium Economy Class'), ('buisness_economy', 'Business Class'), ('first_class', 'First Class')], default='economy', max_length=50)),
                ('passenger_flight', models.CharField(choices=[('adult', 'Adult '), ('children', 'Children'), ('infant', 'Infant')], default='adult', max_length=100)),
                ('price_flight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depart_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app.airport')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app.airport')),
            ],
        ),
    ]
