# Generated by Django 5.1.4 on 2024-12-28 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
