# Generated by Django 5.1.4 on 2024-12-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_flight_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration_flight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
