# Generated by Django 5.1.4 on 2024-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_flight_duration_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='depart_durtation',
        ),
        migrations.AddField(
            model_name='flight',
            name='depart_duration',
            field=models.IntegerField(default=180),
        ),
    ]
