# Generated by Django 5.1.4 on 2024-12-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_airport_airportname_alter_airport_airportcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='depart_location',
            field=models.ForeignKey(limit_choices_to={'city__in': ['Newark', 'Atlanta', 'Los Angeles']}, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_location',
            field=models.ForeignKey(limit_choices_to={'city__in': ['Newark', 'Atlanta', 'Los Angeles']}, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app.airport'),
        ),
    ]
