# Generated by Django 5.1.4 on 2024-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_flight_depart_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airportname',
            field=models.CharField(choices=[('Newark Liberty International Airport', 'Newark Liberty'), ('- Hartsfield-Jackson Atlanta International Airport', 'Hartsfield-Jackson'), ('LAX', 'Los Angeles')], default='Newark Liberty International Airport', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airportcode',
            field=models.CharField(choices=[('EWR', 'EWR'), ('ATL', 'ATL'), ('LAX', 'LAX')], default='EWR', max_length=3),
        ),
    ]
